# Generated by Django 4.0.6 on 2022-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('event_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preacher', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=100)),
                ('verses', models.CharField(max_length=100)),
                ('date_today', models.DateTimeField()),
                ('sermon_summary', models.CharField(max_length=1000)),
            ],
        ),
    ]
